### PR TITLE
Fix map handling with `allOf`/`oneOf` + upgrade `pb33f/libopenapi`

### LINKED ISSUE #100: Maps that utilize `allOf` or `oneOf` result in an empty single nested attribute
### tfplugingen-openapi CLI version

tfplugingen-openapi module: v0.2.0

### OpenAPI Spec File

```YAML
openapi: 3.1.0
info:
  title: EdgeCase API
  version: 1.0.0
paths:
  /map_test:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  map_stringified:
                    $ref: "#/components/schemas/map_allof_oneof_stringified"
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                map_stringified:
                  $ref: "#/components/schemas/map_allof_oneof_stringified"
components:
  schemas:
    map_allof_oneof_stringified:
      description: This is a map with a stringifed value
      type: object
      additionalProperties:
        allOf:
        - $ref: "#/components/schemas/stringable_number"
    stringable_number:
      oneOf:
      - type: string
      - type: number
```

### Generator Config

```YAML
provider:
  name: edgecase

resources:
  map_test:
    create:
      path: /map_test
      method: POST
    read:
      path: /map_test
      method: GET
```

### Expected Behavior

Maps (using the `additionalProperties` property) should be able to leverage nullable and stringable types

```json
{
  "provider": {
    "name": "edgecase"
  },
  "resources": [
    {
      "name": "map_test",
      "schema": {
        "attributes": [
          {
            "name": "map_stringified",
            "map": {
              "computed_optional_required": "computed_optional",
              "element_type": {
                "string": {}
              },
              "description": "This is a map with a stringifed value"
            }
          }
        ]
      }
    }
  ],
  "version": "0.1"
}
```

### Actual Behavior

The map is returned in the IR output as a single nested attribute with no attributes

```json
{
  "provider": {
    "name": "edgecase"
  },
  "resources": [
    {
      "name": "map_test",
      "schema": {
        "attributes": [
          {
            "name": "map_stringified",
            "single_nested": {
              "computed_optional_required": "computed_optional",
              "description": "This is a map with a stringifed value"
            }
          }
        ]
      }
    }
  ],
  "version": "0.1"
}
```

### Additional Information

> This bug was originally discovered in the Kubernetes code generation effort

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by austinvalle**
Closes #100 

This bug was the result of a downstream bug in `pb33f/libopenapi`, where schema's with `additionalProperties` that utilized `allOf`, `anyOf`, or `oneOf` were not being unmarshaled properly. This resulted in the code generator incorrectly determining that a map was a single nested object with no attributes. This was fixed in https://github.com/pb33f/libopenapi/pull/180 and released in [`v0.12.0`](https://github.com/pb33f/libopenapi/releases/tag/v0.12.0)

This PR upgrades `pb33f/libopenapi`, which had some breaking changes to the structure of the code, but no major functional changes outside of the removal of one helper function, which I'll note below.

### CODE REVIEW

File: internal/config/parse.go [hunk 1]
```diff
@@ -139,11 +138,6 @@ func (p Provider) Validate() error {
 		result = errors.Join(result, errors.New("must have a 'name' property"))
 	}
 
-	// All schema refs must be a local, file, or http resolve type
-	if p.SchemaRef != "" && index.DetermineReferenceResolveType(p.SchemaRef) < 0 {
-		result = errors.Join(result, errors.New("'schema_ref' must be a valid JSON schema reference"))
-	}
-
```
Comment (austinvalle) [inline internal/config/parse.go:146]: This is the only removed functionality from upgrading. The `index` package in `pb33f/libopenapi` has been significantly refactored and I can't find an equivalent function for this.

In reality, this validation wasn't super useful anyways, since it never actually checked the spec for the existence of a reference, it just validates that the reference "could" be valid via the syntax.

If we want to replace this validation in the future, we should probably just load the OpenAPI spec provided and check if the reference exists in the spec.

File: internal/mapper/datasource_mapper_test.go [hunk 2]
```diff
@@ -722,18 +722,20 @@ func TestDataSourceMapper_basic_merges(t *testing.T) {
...
-								"deep_nested_bool": base.CreateSchemaProxy(&base.Schema{
-									Type: []string{"boolean"},
-								}),
-								"deep_nested_int64": base.CreateSchemaProxy(&base.Schema{
-									Type:        []string{"integer"},
-									Description: "hey this is an int64!",
-								}),
-							},
-						}),
+						AdditionalProperties: &base.DynamicValue[*base.SchemaProxy, bool]{
```
Comment (austinvalle) [inline internal/mapper/datasource_mapper_test.go:725]: The major breaking change was the structure of the `AdditionalProperties` field, which has been changed from an `any` to a strongly typed value! 🥳

**Review by bflad — APPROVED** [review]
Thank you for the detailed explanations along the way here. Looks good to me. 🚀 Do we want a changelog entry?

**Comment by austinvalle** [comment]
> Thank you for the detailed explanations along the way here. Looks good to me. 🚀 Do we want a changelog entry?

Ah! Yes we definitely need a changelog. Thanks for the reminder! ⚡ 584b878
